select *from customer limit 20

--Q1. What is the total revenue generated by male vs female customers?

select gender,SUM(purchage_amount)as revenue
from customer
group by gender

--Q2. which custom used a discount but still they spent more than average purchage amount?
select customer_id,purchage_amount
from customer
WHERE discount_applied = 'Yes'
  AND purchage_amount >= (
      SELECT AVG(purchage_amount)
      FROM customer
  );

--Q3.which are most top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating::numeric), 2) AS "average_product_rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
--Q4.Compare the average purchage amounts btw standard and express shipping
SELECT
    shipping_type,
    ROUND(AVG(purchage_amount), 2) AS "average_purchase_amount"
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY "average_purchase_amount" DESC;
--Q5.Do subcribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
SELECT
    subscription_status,
	COUNT(customer_id) as total_customers,
    ROUND(AVG(purchage_amount), 2) AS "average_spend",
    ROUND(SUM(purchage_amount), 2) AS "total_revenue"
FROM customer
GROUP BY subscription_status
ORDER BY "average_spend" DESC;
--Q6.Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS "Discount Purchase Percentage"
FROM customer
GROUP BY item_purchased
ORDER BY "Discount Purchase Percentage" DESC
LIMIT 5;
-- Q7. Segment customers into New, Returning, and Loyal
-- based on their total number of previous purchases

SELECT
    CASE
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;
-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),
ranked_products AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;
-- Q9. Are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?

SELECT
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        2
    ) AS subscription_percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY subscription_percentage DESC;

-- Q10. What is the revenue contribution of each age group?

SELECT
    age_group,
    SUM(purchage_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;